---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pl-announcement-config
data:
  # Flip this flag to enable announce kit for changelogs, release notes etc.
  ANNOUNCEMENT_ENABLED: "false"
  # The URL for the announce kit widget.
  ANNOUNCE_WIDGET_URL: ""
