apiVersion: ENC[AES256_GCM,data:FFM=,iv:9PjFj/gfs0V8wMG2vzESY1aYBe+1MxF2Hg+NLVAmh/8=,tag:zuGyACg2RSvhg0aFxJqxSA==,type:str]
kind: ENC[AES256_GCM,data:Z9Mjyw/71n/i,iv:A6TcxuVEjTeXIT1qbnYunpGr0uGXQqhaaE7l0LJWlz4=,tag:ZRzw8e7pt2oW78qeMwDj+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/2WBJJU/lVyOxZkB/XPJ3w==,iv:G8zsvdMcC1idCrJDSvA3iiLiCevP1KG3tlu3sRVAddQ=,tag:92Zct1g/btdrq1ZydYFHzA==,type:str]
data:
    PL_SENTRY_DSN: ENC[AES256_GCM,data:lkm+4x+2MzwpbvPUICFq0IyRmDcbvOP5ZAuW3DDRRsoCATjKIdV86yhD6tUfcRTXm+fSR55WLj6+LthNA+qHA3yG7MEM4MTCmGzd1oa9t7eScF9i/CGXaOIf81VlcuI=,iv:FJGkoNB0rpv9RnnuJxatiIRavALuAnhWeXuBz5rM658=,tag:V6TtQBNayrH6heWuwNQadQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-staging/locations/global/keyRings/staging-keyring/cryptoKeys/sops-key
        created_at: '2024-06-10T16:30:02Z'
        enc: CiQAVx9wUS9eHaHXiqYpPVbHTZuO9AKn8hKq65Jr4n3z8O0M+l4SSQCi7xzh+YbcNz0WCPlMWb55BlW5WCPuLg1D/bRAImN3F0XRlQtmOyW8jKVoBVpDZQ/fcuAFjAJsp8AL28/AEnsUVVfdksPUTe8=
    azure_kv: []
    lastmodified: '2024-06-10T16:30:02Z'
    mac: ENC[AES256_GCM,data:H98at5o/+wrs40ca+TIwDjpfkz+CxC2Pk+mPUEhFom76MZ14QV+zpnq8fnISBl8eHcpBCzSvhkTo347zL7abLnERm6s7zMUYNrA8YhX+Bk/RYsKd3BZejqdUOj4/2t17Qhfupo+cSvQPs/pfnea9hWqpDezSokTiBTtyro3U4f0=,iv:a3MIPi+zTtB24Oh0eycXcOvSoNPBO86ALjpI94ZOHGg=,tag:nJmpsTnsrBzb8LjocSYLew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
