apiVersion: ENC[AES256_GCM,data:7Co=,iv:qbc+ST5t28c3/5qm1f70akOrTThfI7HkJ1wkxEYn6v0=,tag:6Ez7N9ZTW+E1+OFdBkVKyg==,type:str]
kind: ENC[AES256_GCM,data:YZVl0BpuhZSE,iv:vVQwJ9Keh4ARL33QsuKZBbB7uvqaYWd2DdBqwtBDuWw=,tag:X14bixfETIlSzQeLODDtqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zJ2Z4eXUd6tRXHIg3ODI3g==,iv:ifTg/A9rFkc3r4k9uh8VvWxB8av189rAaYJERqMD+KA=,tag:W1GPyb6YWNe2ByT9Y6yDKQ==,type:str]
#ENC[AES256_GCM,data:BzG61E9COWfMdeWSCUYWSTNpmsOFSJ5y0NRYxdTF4g5JZHX0SLp9mkldpf8Xyk15fWmvvjZaGb0tDe6nJ/qnCg+WI9N0D/Uit4rC6FceJYBl+55Z/KZPVwZhGO/c,iv:N87lpbYxVsha0l5XoAwUG2bavfldrqui1Pmicbe1JXQ=,tag:7jVa2h978dSoF59iwjV7Tw==,type:comment]
data:
    PL_SENTRY_DSN: ENC[AES256_GCM,data:MWYjM7Q+L6Uu4HRdmadRu1J2xJ4Z2OX3Ezvny03fZsplKE9jCnRt+/D0+nV2Z9byS3RExyXooSpbQr1q8VctzZyp4qoexB12+7O+MYqbcx0a4LGFtQWoXvcRSiFHpyU=,iv:He+UaWQRHQrFLSiAa4cJ+Fa3/QVa6YNZlsJA6L94igY=,tag:QrYC5zUOLov0Eevg2xMiQg==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-staging/locations/global/keyRings/staging-keyring/cryptoKeys/sops-key
        created_at: '2024-06-10T06:01:05Z'
        enc: CiQAVx9wUQNKRt7UpKo166V0A+XmHvq9ZyouKBzyHqVbMdgUBpUSSQCi7xzhY7n10pEF+DKNIqrMcIrSBiDlijm4Rs6yUzMC541UMw+47mi1p9LTSVulizaxODMqeSq6ijex1GMiQGWMNePkQh9gFus=
    azure_kv: []
    lastmodified: '2024-06-10T06:01:05Z'
    mac: ENC[AES256_GCM,data:OFtxDjf7duhCokmcHhqTTcqwDu6hJ5j1hHkkTd2o1HZegNrTKP2h61eGkrw7h0GNP/YyOWz5WeP4JKhr+ebEpz3zQnlXamDKFUlIX+u+wRciwkUtDmFzRV+SfKndoAWAN1l3tAGBGx4guyC0MmC5S2MLeMjIrsFVBofFCjOSsDo=,iv:3ZlrNgZiXQLuqcoZ3qEWifByFd1bB6aJleM0G6hWjSA=,tag:SlEaHSllLxxebnRBnI7mbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
