- op: replace
  path: /metadata/annotations
  value:
    kubernetes.io/ingress.class: gce-internal
    kubernetes.io/ingress.regional-static-ip-name: cosmic-cloud-testing-ingress-internal-ip
- op: add
  path: /spec/tls
  value:
  - secretName: testing-getcosmic-ai-tls
