apiVersion: ENC[AES256_GCM,data:LPY=,iv:pTp8jG9IuCqx3rN1MdcaZaSYzzguhGaD54jDKEPS0uY=,tag:SoZqU7jl+v5IksE+R8Z07w==,type:str]
kind: ENC[AES256_GCM,data:dIYzy3GTsA5y,iv:GOyopDOtw5PXMq6f0lz2SJJHYMEW6qAmMZsdniIXpXk=,tag:J5pds1rW6cQYNuiS0BVKzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5DciIzysJE0wCD/S,iv:HIwNSjTo3KRMSkB32xTt/bCv3bEichGjvwi6B/V68qo=,tag:pzcwi5A2MSJttM8GY+ZazQ==,type:str]
data:
    PL_LD_CLIENT_ID: ""
    PL_LD_SDK_KEY: ""
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-dev/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2024-06-10T16:32:10Z'
        enc: CiQAvs16itcUt1FxJamEoKzzDpOh8iQQpzFfrbnxVAjdLWPuvOUSSQCynFbJXp9IdbJslSCQ84mUG3XCQx+rV4EgBqOn87EY5QKZIQVGPa59OAVwatNCVw3qrnpRo+O1MOzR+iGvddPzt3DUGH2f6XE=
    azure_kv: []
    lastmodified: '2024-06-10T16:32:10Z'
    mac: ENC[AES256_GCM,data:i35sCOSmhbX50quuGUlry2sGWZjo8Ciex1O4AqJ4LaitfClkSPiaDRAARtyhfT60HZ1WAx2vUZWWa62rcdT6WlCbhglfTKicr1kuqzWeWFaERzb5+a0QTGTRpqLng20pgbJRMShhuRW96JZskfR8pkjh7rHnKyU9urWl/tkwbm4=,iv:/2t1hTxIGBoHazeIjNXGtXj3TQGmiXxxxEBBqUmHFWM=,tag:YFjDcc0k4W5/Qo1iKKSy/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
