apiVersion: ENC[AES256_GCM,data:p4s=,iv:krG3BP2vlvoaIREWqwU+ihbqUmx+28auD45bn2I5VKE=,tag:8HlLF4feR3WaUej7yZkSFg==,type:str]
kind: ENC[AES256_GCM,data:8HHd1ILTzFNW,iv:pnpwW8f95jvvBt/q0NBtkh+ce4qZke1zp0pWAKA848o=,tag:URptpiZk+5P4c9w5u1M1EQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xWI/cVOHwG8WGb4rzs01,iv:Wmkbuit+i9mHHvaWB+ci05EmvOhZ65Gzewrdqp2QmuU=,tag:t58XopxRTdqluQOV3cB7Dw==,type:str]
    namespace: ENC[AES256_GCM,data:z0QGss3yJeM3Q2U=,iv:xMr4m8GVJY5HiZWlvXeGeRjAO12bWWJsiKfunfM69Ns=,tag:W0HlvNqvJJVlAZFLaApoyg==,type:str]
data:
    PL_OAUTH_PROVIDER: ENC[AES256_GCM,data:dKassss=,iv:Au6La5qfgzJs9l4EIfaekIhPNBSmqDWIQbCCllWCCLI=,tag:Qn34gV6JD01hacatU7P2TQ==,type:str]
    PL_AUTH_URI: ENC[AES256_GCM,data:sHa+FPb9omYZRJnRtP/ipeBuFld5p6JWEJgOqAkoi+QD,iv:HGI3QhtFmINOgkSpT6Wpeeb5GsMWgCr/bf8cW0jYZ38=,tag:pw1Oe4qSZVqs7yCB5q1gZA==,type:str]
    PL_AUTH_CLIENT_ID: ENC[AES256_GCM,data:VfT05kZ1dQQWRi5SHZo8CFz0j3G0KgCSe+AvpwQYVSQ=,iv:lhDb+Ws2SMMT7TnnFoSj7H8CuweG5ONFGVcc6yd+zHM=,tag:aO651QGSN36VYjMT06uCXw==,type:str]
    PL_AUTH_EMAIL_PASSWORD_CONN: ENC[AES256_GCM,data:J7sRrY7TFboXi5rXdxqRaJZIaWM=,iv:s84VzdSOdAAjAd8D7+uJyO6i9FDG5kjsKtp4OpPRxqU=,tag:Wiz117RQokMfdckk8sklpA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-dev/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2024-06-07T03:31:03Z'
        enc: CiQAvs16itB3wbrHisnF3Vmoqs1ZepW8MenOcy76W1WnIHstJyISSQCynFbJqYYlxUAl4Jgzdi2nGksMABZ6KHaUEKz1IwrShZRsABgNnpcmk8NwVlfDLMUEZepbi1Xdwsw2KxGE7V7JcEB1xnrQygo=
    azure_kv: []
    lastmodified: '2024-06-07T03:31:03Z'
    mac: ENC[AES256_GCM,data:aQCBTB5xfXq7elWxrBLlLyem2ZDblCPaSdXYFtI29Jqkpb2z8E17BEnV5A5glgnGpJ2yRKNMIe2PHNF5h30etTG3wSWbllPbgUXR4ofkVjpPdT9X20ILj4WzYu72IXxa/TStzRH5XoJRN3MDNvDFiHTYFGGwo4xejRtwP8olrNc=,iv:M1OmG2vx+X1nDJh1aGdVb+cYqL+ZbtNY8mVPlXurOns=,tag:cxmmV9pve484kCAwINP14A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
