---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cloud-ingress-managed-cert-noslackin
spec:
  domains:
  - testing.getcosmic.ai
  - work.testing.getcosmic.ai
  - docs.testing.getcosmic.ai
