---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
resources:
- ../../../k8s/cloud_deps/prod
patches:
- path: node_selector_patch.yaml
  target:
    kind: StatefulSet
- path: elastic_node_selector_patch.yaml
  target:
    kind: Elasticsearch
