---
- op: test
  path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
  value: pixie-cloud-prod-external-ipaddr
- op: replace
  path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
  value: cosmic-cloud-prod-ingress-ip
