apiVersion: ENC[AES256_GCM,data:rUs=,iv:EtW6CRmknnk1483QXFRw5JcYMw2x50ou/FmxCGX2ftU=,tag:NUYyo3yvIMRJLto1qJIiWw==,type:str]
kind: ENC[AES256_GCM,data:qjUlNHKfC8f0,iv:0RA6Jw7LRvwvHFwFVUsbLaZrrgPjJlV3vbBoLUu7xeg=,tag:tThyKqw5DEyRq7Kk1wbWfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:joz8NCJawpjAG6xN,iv:Cyfsose6s4evUvEP/vPKDGyVJ32tlqlGNYLgTI/ryNY=,tag:ItameXZ3uF9+yQp/UhIHwA==,type:str]
data:
    PL_LD_CLIENT_ID: ""
    PL_LD_SDK_KEY: ""
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-prod/locations/global/keyRings/prod-keyring/cryptoKeys/sops-key
        created_at: '2024-06-25T06:21:50Z'
        enc: CiQAcY70Mas00GBaeV4bHc+03L6mwPHnlw6xNvJ7yV6oNzu/7KYSSQAjULcWwTr8cjlj1s+OOICPhLk+Z8OeixlQxfGWCF4GFqtqm91rnG2QSUh0+vbq6eXBUDgx5VORmrsp4t5uj0MJR/2hwVQ7glc=
    azure_kv: []
    lastmodified: '2024-06-25T06:21:51Z'
    mac: ENC[AES256_GCM,data:mQGXOoNrpMilAM/bCdX6yqpbPOzHQwYlHLQllj3+/MraYlJvTDWWqvfJCfZyICxAc8knmwuhu8RoO15X6WZ/J293jNdcpCizISmkyCO4/L+in9QdmFWvfUL6V2LxFdRiukuRspP9pdikSbED3w09/P72PYG0RdfZtH4n0++U6f8=,iv:/sz/MmKZ/GcAnX9VGcISrXlBRFkeWcvPWquZjbj/HMo=,tag:2EaGn37J1tLws0bq48FMwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
