apiVersion: ENC[AES256_GCM,data:gTw=,iv:nDFGsOpE/BtsizTDIUPKv2Sy1VWPnCxhDnjvdzMjksc=,tag:xrAEVwyrdn+2paALZHjChQ==,type:str]
kind: ENC[AES256_GCM,data:UCa85ivmtFnC,iv:yV7GYvLYJh5d7cW1y7VKyLb6kH25+6A/TYTUjVTQBkE=,tag:BNf8QDpyNP2Jo0MgqMfb+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GsrByosgZZYrylxPQ1aVb1f8ymQ=,iv:9NYYejvycOYwM5pO3THgwERBj08H10+8jYF7eCiLWzg=,tag:UBvB40Zf7g57sWPWDwHGCw==,type:str]
data:
    PL_PROD_SENTRY: ENC[AES256_GCM,data:mqa65dXZ7hJAMsSAXQ1I5H8TxVNkE2kbf1WmOFufxbAkBbnkqChrbLlxWLudn6AlDpjynkKwHZGKPa6ob99gmILzL4ItmBpEBg1egH/dLlcY1D/iEYn/rq1zWNw/sdY=,iv:OrWW4WL4gt8sUyTo1po30U1OHITUhdS3xjcmceTycpo=,tag:QDqyZxK2+exUZA/lb0VCcg==,type:str]
    PL_DEV_SENTRY: ENC[AES256_GCM,data:fGfHX3CjotCiCc9N+2S83Lj4AMjtZkj0B7tpmcS3Kus4Km5cq0q1VoD+tvvzBpQh6D38XnHtT9G3jZp7BU/WGj/segGQV4nZDW4hO+HlcIvJ5dCKzIcewq2cv84qIQ0=,iv:HHruyNIdTFUUsftflSD48VTpHL5b3bJLJLTOgr+X/rM=,tag:sJn/vjO7Zjn9V5tFyN9MnA==,type:str]
    PL_OPERATOR_SENTRY: ENC[AES256_GCM,data:OGY0P3+tkewqsNvTLy5DO7qB+5zKXy1uhlTOlntbax/DccETNB21Yq6ARpiH4Ap5X0itTaQi0HfBDUqDB8BzUuugVjSD1ZhV3SVy9RHKuy1KBPOTzEWvFgbry2yf9YQ=,iv:8W6CB9xyJCvoDuz2R7khgOWe708u7NxlH7qXpqBN5CE=,tag:EHhFbKMeCKPoChNoj0Qqcw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/csmc-prod/locations/global/keyRings/prod-keyring/cryptoKeys/sops-key
        created_at: '2024-06-25T06:28:53Z'
        enc: CiQAcY70MbJTeXENHuOJRq3TgW10b429nvO62KMBpe3cbYXdlDsSSQAjULcWQvi/czSkjd9zO9f6S8W3OoSNUSO4NmJiy+jwkgF2PvZDWvZKgpm/NPCi965LZLtIPomim6XZ42nxzLJuFs7itrrp9mo=
    azure_kv: []
    lastmodified: '2024-06-25T06:28:53Z'
    mac: ENC[AES256_GCM,data:GsgbGbrFbzuvmFwkwsw1HjlObF8dP4ndELvLj+/jHY0jxcNA4G6cP37GIZDfN7IOmiHZZztXlvRX/yS0fCtAIGqmWg+ig4JX/OP0jsFIwIQAHnXJNQCtsX4y0+oVPNUMbvdpwS84So/eCxltHy0NEoRIk8IQSSf0Fzn3Tr3leE8=,iv:fHGGSQQjFBb9FRmdX4GIfGi/RSkcFoX5xqGam4ZsKtg=,tag:ll70JNte5LqTnnYvfzCHsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
