---
# Master node.
- op: replace
  path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
  value: 10Gi

- op: add
  path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/storageClassName
  value: ssd

# Data node.
- op: replace
  path: /spec/nodeSets/1/volumeClaimTemplates/0/spec/resources/requests/storage
  value: 15Gi

- op: add
  path: /spec/nodeSets/1/volumeClaimTemplates/0/spec/storageClassName
  value: ssd
